# Generated by Django 2.2.7 on 2019-12-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxClaim', models.DecimalField(decimal_places=4, max_digits=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxcredit_name', to='bbirmsite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startAmount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('endAmount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gov_type', models.CharField(choices=[('F', 'Federal'), ('P', 'Provincial'), ('M', 'Municipal')], default='F', max_length=1)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxbracket_name', to='bbirmsite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='EIRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maxPerYear', models.DecimalField(decimal_places=4, max_digits=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eirate_name', to='bbirmsite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='CPPRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemption', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('maxPerYear', models.DecimalField(decimal_places=4, max_digits=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpprate_name', to='bbirmsite.Year')),
            ],
        ),
    ]
